### ISSUE TITLE
KeyError: 'readTimes'

### ISSUE THREAD

**Issue by anuxs** [malinkang/weread2notion#49]
从重构版本更新那天起就一直报同样的错误：
`Run github_heatmap weread  --weread_cookie "***" --year 2018-2023 --me "" --with-animation --background-color=#ffffff --track-color=#ACE7AE --special-color1=#69C16E --special-color2=#549F57 --dom-color=#EBEDF0 --text-color=#000000

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/bin/github_heatmap", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/github_heatmap/cli.py", 
line 182, in main
    run()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/github_heatmap/cli.py", 
line 89, in run
    tracks, years = loader.get_all_track_data()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/github_heatmap/loader/weread_loader.py", line 50, in get_all_track_data
    self.make_track_dict()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/github_heatmap/loader/weread_loader.py", line 41, in make_track_dict
    readTimes = dict(sorted(api_data["readTimes"].items(), reverse=True))

KeyError: 'readTimes'

Error: Process completed with exit code 1.` 

刚开始以为是notion模板的问题，把模板删除了重新复制了，更新了database_id，还是报错。

**Comment by wenghengcong** [comment]
同样遇到该问题

**Comment by wenghengcong** [comment]
同样遇到此问题：可以将 /weread2notion/.github/workflows.yml  中的 weread heatmap 关掉就行
<img width="1334" alt="截屏2023-12-29 12 58 11" src="https://github.com/malinkang/weread2notion/assets/3964406/3cd204ee-6c92-490c-9fe2-e198f844d761">

**Comment by malinkang** [comment]
是不是cookie过期了？
